#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Interactive deployer for the Claude apps gateway on Google Cloud.
# Prompts for configuration, then hands off to Terraform or plain gcloud.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

CONFIG_FILE="${SCRIPT_DIR}/config.env"
TFVARS_FILE="${SCRIPT_DIR}/terraform/terraform.tfvars"

DEFAULT_GATEWAY_VERSION="2.1.206"
DEFAULT_REGION="us-east5"

# ---------------------------------------------------------------------------
# Terraform path
# ---------------------------------------------------------------------------
deploy_terraform() {
  require_cmd terraform "Install from https://developer.hashicorp.com/terraform/downloads"

  # Answers are written into terraform.tfvars rather than exported as TF_VAR_*.
  # Terraform ranks terraform.tfvars ABOVE environment variables, so a stale
  # file on disk would silently win over anything exported here — the exact
  # trap that would deploy your answers into someone else's project.
  info "Writing $(basename "$TFVARS_FILE") from your answers..."
  cat > "$TFVARS_FILE" <<EOF
# Generated by deploy.sh — edits here are overwritten on the next run.
# Gitignored: contains the OAuth client secret.

project_id      = "${PROJECT_ID}"
region          = "${REGION}"
gateway_version = "${GATEWAY_VERSION}"

oauth_client_id      = "${OAUTH_CLIENT_ID}"
oauth_client_secret  = "${OAUTH_CLIENT_SECRET}"
allowed_email_domain = "${ALLOWED_DOMAIN}"

ingress                = "${INGRESS}"
invoker_mode           = "${INVOKER_MODE}"
gateway_public_url     = "${GATEWAY_PUBLIC_URL}"
proxy_only_subnet_cidr = "${PROXY_ONLY_SUBNET_CIDR}"
EOF
  chmod 600 "$TFVARS_FILE"
  ok "Wrote $(basename "$TFVARS_FILE")"

  pushd "${SCRIPT_DIR}/terraform" >/dev/null

  info "Initializing Terraform..."
  terraform init -input=false

  info "Applying (first pass: build image and create infrastructure)..."
  terraform apply -input=false -auto-approve

  GATEWAY_URL="$(terraform output -raw gateway_public_url)"

  # Internal-only topology has a chicken-and-egg: the gateway needs its own URL
  # to build the IdP redirect_uri, but Cloud Run only mints that URL once the
  # service exists. Because the rendered YAML refers to ${GATEWAY_PUBLIC_URL}
  # rather than baking the URL in, closing the loop is a one-line env-var
  # update — no new secret version, no second full apply.
  if [[ "$INGRESS" == "INGRESS_TRAFFIC_INTERNAL_ONLY" && -z "$GATEWAY_PUBLIC_URL" ]]; then
    info "Pinning the generated URL into the service: ${GATEWAY_URL}"
    gcloud run services update claude-gateway \
      --region="$REGION" --project="$PROJECT_ID" \
      --update-env-vars="GATEWAY_PUBLIC_URL=${GATEWAY_URL}" --quiet

    # Persist it so the next apply does not plan the placeholder back in.
    GATEWAY_PUBLIC_URL="$GATEWAY_URL"
    sed -i.bak "s|^gateway_public_url .*|gateway_public_url     = \"${GATEWAY_URL}\"|" terraform.tfvars
    rm -f terraform.tfvars.bak
    save_config "$CONFIG_FILE" PROJECT_ID REGION GATEWAY_VERSION OAUTH_CLIENT_ID \
      OAUTH_CLIENT_SECRET ALLOWED_DOMAIN TOPOLOGY INGRESS GATEWAY_PUBLIC_URL \
      PROXY_ONLY_SUBNET_CIDR INVOKER_MODE
  fi

  MANAGED_SETTINGS="$(terraform output -raw managed_settings_snippet)"
  popd >/dev/null

  print_next_steps
}

# ---------------------------------------------------------------------------
# gcloud path
# ---------------------------------------------------------------------------
deploy_gcloud() {
  export PROJECT_ID REGION GATEWAY_VERSION OAUTH_CLIENT_ID OAUTH_CLIENT_SECRET \
    ALLOWED_DOMAIN INGRESS INVOKER_MODE GATEWAY_PUBLIC_URL PROXY_ONLY_SUBNET_CIDR

  bash "${SCRIPT_DIR}/gcloud-scripts/deploy-gcloud.sh"

  GATEWAY_URL="${GATEWAY_PUBLIC_URL:-$(gcloud run services describe claude-gateway \
    --region="$REGION" --project="$PROJECT_ID" --format='value(status.url)')}"
  MANAGED_SETTINGS="$(printf '{"forceLoginMethod":"gateway","forceLoginGatewayUrl":"%s","parentSettingsBehavior":"merge"}' "$GATEWAY_URL")"

  print_next_steps
}

# ---------------------------------------------------------------------------
# Closing instructions
# ---------------------------------------------------------------------------
print_next_steps() {
  banner "Deployment complete"
  echo -e "Gateway URL: ${BOLD}${GATEWAY_URL}${NC}"
  echo ""
  echo -e "${BOLD}The gateway is running but no developer can use it yet.${NC}"
  echo "Three steps remain, in order:"
  echo ""
  echo -e "${BOLD}1. Authorize the redirect URI${NC}"
  echo "   Add this exact URI to your OAuth client's authorized redirect URIs:"
  echo -e "   ${YELLOW}${GATEWAY_URL}/oauth/callback${NC}"
  echo ""
  echo -e "${BOLD}2. Confirm the host resolves privately${NC}"
  echo "   /login rejects the gateway if its hostname resolves to any public"
  echo "   address. From a developer machine on the corporate network:"
  echo -e "   ${YELLOW}nslookup $(echo "$GATEWAY_URL" | sed -e 's|https://||' -e 's|/.*||')${NC}"
  echo "   Every address returned must be private. See docs/NETWORKING.md."
  echo ""
  echo -e "${BOLD}3. Push managed settings via MDM${NC}"
  echo "   There is no gateway option a developer can pick manually at /login."
  echo "   Deploy this to each machine's managed settings file:"
  echo -e "   ${YELLOW}${MANAGED_SETTINGS}${NC}"
  echo "   See docs/CLIENT-SETUP.md for per-OS paths."
  echo ""
}

banner "Claude apps gateway on Google Cloud — Deployer"

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
info "Checking prerequisites..."
require_cmd gcloud "Install from https://cloud.google.com/sdk/docs/install"
require_cmd curl   "Install curl, or download the gateway binary manually."
ensure_gcloud_auth

# ---------------------------------------------------------------------------
# 2. Configuration
# ---------------------------------------------------------------------------
load_config "$CONFIG_FILE"

echo ""
info "Project and region"
: "${PROJECT_ID:=$(gcloud config get-value project 2>/dev/null || echo "")}"
ask PROJECT_ID "GCP project ID"
require_var PROJECT_ID

echo ""
echo "  Pick a region where the Claude models you need are published in Model"
echo "  Garden. Model availability is per-region and is the real constraint."
ask REGION "GCP region" "$DEFAULT_REGION"

ask GATEWAY_VERSION "Claude Code / gateway version to deploy" "$DEFAULT_GATEWAY_VERSION"

echo ""
info "Identity provider (Google Workspace OAuth 2.0 web-application client)"
ask OAUTH_CLIENT_ID "OAuth client ID"
require_var OAUTH_CLIENT_ID

if [[ -n "${OAUTH_CLIENT_SECRET:-}" ]]; then
  confirm "Reuse the saved OAuth client secret?" || OAUTH_CLIENT_SECRET=""
fi
[[ -n "${OAUTH_CLIENT_SECRET:-}" ]] || ask_secret OAUTH_CLIENT_SECRET "OAuth client secret (hidden)"
require_var OAUTH_CLIENT_SECRET

echo ""
echo "  This domain is the gateway's entire access-control list: sign-ins from"
echo "  any other domain are rejected."
ask ALLOWED_DOMAIN "Allowed email domain (e.g. acme.com)"
require_var ALLOWED_DOMAIN
if [[ "$ALLOWED_DOMAIN" == "example.com" ]]; then
  die "example.com is the documentation placeholder. Use your real Workspace domain."
fi

# ---------------------------------------------------------------------------
# 3. Network topology
# ---------------------------------------------------------------------------
# Claude Code's /login refuses any self-hosted gateway whose hostname resolves
# to a public address, so there is no public option to offer here. Both choices
# are private; they differ in which plumbing you already have.
echo ""
banner "Network topology"
cat <<'EOF'
Claude Code only signs in to a gateway whose hostname resolves to private
addresses. Both options below are private. Full detail: docs/NETWORKING.md

  1) Internal ingress, no load balancer            (fewest resources)
     Keeps the *.run.app URL. Only works if your org ALREADY runs a Private
     Service Connect endpoint for Google APIs plus a Cloud DNS private zone
     resolving *.run.app to it, with routing from developer networks.

  2) Internal Application Load Balancer            (self-contained)
     You provision an internal ALB, an internal DNS name, and a TLS cert, then
     point the gateway at that hostname. More to build, but it does not depend
     on pre-existing *.run.app private resolution.

If neither is true of your environment yet, stop and read docs/NETWORKING.md
before deploying — the deploy will succeed and sign-in will not.
EOF
echo ""
ask TOPOLOGY "Select topology [1 or 2]" "1"

case "$TOPOLOGY" in
  1)
    INGRESS="INGRESS_TRAFFIC_INTERNAL_ONLY"
    GATEWAY_PUBLIC_URL="${GATEWAY_PUBLIC_URL:-}"
    PROXY_ONLY_SUBNET_CIDR=""
    ok "Internal ingress. public_url will be set to the generated *.run.app URL."
    ;;
  2)
    INGRESS="INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
    echo ""
    echo "  The hostname your internal ALB serves, including scheme."
    ask GATEWAY_PUBLIC_URL "Gateway public URL (e.g. https://claude-gateway.internal.acme.com)"
    require_var GATEWAY_PUBLIC_URL
    ask PROXY_ONLY_SUBNET_CIDR "Proxy-only subnet CIDR for ${REGION}"
    require_var PROXY_ONLY_SUBNET_CIDR
    warn "This deployer does not create the ALB, DNS record, or certificate."
    warn "See docs/NETWORKING.md for the load balancer build."
    ;;
  *)
    die "Invalid topology selection: $TOPOLOGY"
    ;;
esac

echo ""
echo "  Cloud Run's invoker check must be open or disabled — the gateway runs"
echo "  its own OIDC and its clients carry no GCP token. 'allusers' is the"
echo "  default; choose 'external' if Domain Restricted Sharing blocks it."
ask INVOKER_MODE "Invoker mode [allusers|external]" "allusers"

save_config "$CONFIG_FILE" PROJECT_ID REGION GATEWAY_VERSION OAUTH_CLIENT_ID \
  OAUTH_CLIENT_SECRET ALLOWED_DOMAIN TOPOLOGY INGRESS GATEWAY_PUBLIC_URL \
  PROXY_ONLY_SUBNET_CIDR INVOKER_MODE

# ---------------------------------------------------------------------------
# 4. Gateway binary
# ---------------------------------------------------------------------------
echo ""
fetch_gateway_binary "$GATEWAY_VERSION" "${SCRIPT_DIR}/templates/claude"

# ---------------------------------------------------------------------------
# 5. Deployment method
# ---------------------------------------------------------------------------
echo ""
banner "Deployment method"
echo "  1) Terraform  — declarative, tracks state, supports clean teardown"
echo "  2) gcloud CLI — imperative, no state file, easier to read line by line"
echo ""
ask DEPLOY_METHOD "Select method [1 or 2]" "1"

case "$DEPLOY_METHOD" in
  1) deploy_terraform ;;
  2) deploy_gcloud ;;
  *) die "Invalid selection: $DEPLOY_METHOD" ;;
esac
